# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_AudioControl.ui'
#
# Created: Mon Oct 12 19:52:46 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(714, 874)
        MainWindow.setMaximumSize(QtCore.QSize(800, 874))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setMaximumSize(QtCore.QSize(800, 856))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 694, 854))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setMinimumSize(QtCore.QSize(645, 400))
        self.groupBox.setMaximumSize(QtCore.QSize(645, 400))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setMinimumSize(QtCore.QSize(625, 310))
        self.groupBox_4.setMaximumSize(QtCore.QSize(625, 310))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.qwtPlot_Zeitsignal = Qwt5.QwtPlot(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlot_Zeitsignal.sizePolicy().hasHeightForWidth())
        self.qwtPlot_Zeitsignal.setSizePolicy(sizePolicy)
        self.qwtPlot_Zeitsignal.setMinimumSize(QtCore.QSize(571, 250))
        self.qwtPlot_Zeitsignal.setMaximumSize(QtCore.QSize(16777215, 300))
        self.qwtPlot_Zeitsignal.setObjectName(_fromUtf8("qwtPlot_Zeitsignal"))
        self.horizontalLayout.addWidget(self.qwtPlot_Zeitsignal)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox_Audio_In = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_Audio_In.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_Audio_In.setObjectName(_fromUtf8("comboBox_Audio_In"))
        self.horizontalLayout_2.addWidget(self.comboBox_Audio_In)
        self.pushButton_Start = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Start.sizePolicy().hasHeightForWidth())
        self.pushButton_Start.setSizePolicy(sizePolicy)
        self.pushButton_Start.setMinimumSize(QtCore.QSize(50, 10))
        self.pushButton_Start.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_Start.setObjectName(_fromUtf8("pushButton_Start"))
        self.horizontalLayout_2.addWidget(self.pushButton_Start)
        self.pushButton_Stop = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Stop.sizePolicy().hasHeightForWidth())
        self.pushButton_Stop.setSizePolicy(sizePolicy)
        self.pushButton_Stop.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_Stop.setObjectName(_fromUtf8("pushButton_Stop"))
        self.horizontalLayout_2.addWidget(self.pushButton_Stop)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lcdNumber_Vcc = QtGui.QLCDNumber(self.groupBox_7)
        self.lcdNumber_Vcc.setMaximumSize(QtCore.QSize(50, 20))
        self.lcdNumber_Vcc.setAutoFillBackground(False)
        self.lcdNumber_Vcc.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumber_Vcc.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_Vcc.setLineWidth(1)
        self.lcdNumber_Vcc.setMidLineWidth(0)
        self.lcdNumber_Vcc.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_Vcc.setObjectName(_fromUtf8("lcdNumber_Vcc"))
        self.horizontalLayout_3.addWidget(self.lcdNumber_Vcc)
        self.label_3 = QtGui.QLabel(self.groupBox_7)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lcdNumber_2_Ausgang = QtGui.QLCDNumber(self.groupBox_7)
        self.lcdNumber_2_Ausgang.setMaximumSize(QtCore.QSize(50, 20))
        self.lcdNumber_2_Ausgang.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumber_2_Ausgang.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_2_Ausgang.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_2_Ausgang.setObjectName(_fromUtf8("lcdNumber_2_Ausgang"))
        self.horizontalLayout_3.addWidget(self.lcdNumber_2_Ausgang)
        self.label_6 = QtGui.QLabel(self.groupBox_7)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.gridLayout.addWidget(self.groupBox_7, 5, 0, 1, 4)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_6.setMinimumSize(QtCore.QSize(303, 292))
        self.groupBox_6.setMaximumSize(QtCore.QSize(303, 292))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_6)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 2, 4, 1, 1)
        self.Thermo_Vcc = Qwt5.QwtThermo(self.groupBox_6)
        self.Thermo_Vcc.setMaximumSize(QtCore.QSize(16777215, 250))
        self.Thermo_Vcc.setObjectName(_fromUtf8("Thermo_Vcc"))
        self.gridLayout_3.addWidget(self.Thermo_Vcc, 3, 1, 3, 1)
        self.Thermo_Ausgang = Qwt5.QwtThermo(self.groupBox_6)
        self.Thermo_Ausgang.setMaximumSize(QtCore.QSize(16777215, 250))
        self.Thermo_Ausgang.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Thermo_Ausgang.setAutoFillBackground(False)
        self.Thermo_Ausgang.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Thermo_Ausgang.setBorderWidth(2)
        self.Thermo_Ausgang.setMaxValue(100.0)
        self.Thermo_Ausgang.setMinValue(-100.0)
        self.Thermo_Ausgang.setPipeWidth(10)
        self.Thermo_Ausgang.setProperty("value", 0.0)
        self.Thermo_Ausgang.setObjectName(_fromUtf8("Thermo_Ausgang"))
        self.gridLayout_3.addWidget(self.Thermo_Ausgang, 4, 4, 1, 1)
        self.gridLayout.addWidget(self.groupBox_6, 2, 0, 3, 4)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 7, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.comboBox_Abfragerate = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_Abfragerate.setObjectName(_fromUtf8("comboBox_Abfragerate"))
        self.gridLayout.addWidget(self.comboBox_Abfragerate, 0, 8, 1, 1)
        self.radioButton_Kanal1 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_Kanal1.setObjectName(_fromUtf8("radioButton_Kanal1"))
        self.gridLayout.addWidget(self.radioButton_Kanal1, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setMinimumSize(QtCore.QSize(255, 292))
        self.groupBox_5.setMaximumSize(QtCore.QSize(255, 292))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lcdNumber_Temperatur = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdNumber_Temperatur.setMaximumSize(QtCore.QSize(75, 20))
        self.lcdNumber_Temperatur.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_Temperatur.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_Temperatur.setObjectName(_fromUtf8("lcdNumber_Temperatur"))
        self.gridLayout_4.addWidget(self.lcdNumber_Temperatur, 1, 2, 1, 2)
        self.TextLabel = Qwt5.QwtTextLabel(self.groupBox_5)
        self.TextLabel.setObjectName(_fromUtf8("TextLabel"))
        self.gridLayout_4.addWidget(self.TextLabel, 6, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setMinimumSize(QtCore.QSize(0, 50))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setMinimumSize(QtCore.QSize(0, 50))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 3, 0, 1, 1)
        self.lcdNumber_Strom = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdNumber_Strom.setMaximumSize(QtCore.QSize(75, 20))
        self.lcdNumber_Strom.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_Strom.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_Strom.setObjectName(_fromUtf8("lcdNumber_Strom"))
        self.gridLayout_4.addWidget(self.lcdNumber_Strom, 0, 2, 1, 1)
        self.lcdNumber_Volume = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdNumber_Volume.setMaximumSize(QtCore.QSize(75, 20))
        self.lcdNumber_Volume.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_Volume.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_Volume.setObjectName(_fromUtf8("lcdNumber_Volume"))
        self.gridLayout_4.addWidget(self.lcdNumber_Volume, 3, 2, 1, 2)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setMinimumSize(QtCore.QSize(0, 50))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setMinimumSize(QtCore.QSize(0, 50))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.lcdNumber_MUX = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdNumber_MUX.setMaximumSize(QtCore.QSize(75, 20))
        self.lcdNumber_MUX.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber_MUX.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_MUX.setObjectName(_fromUtf8("lcdNumber_MUX"))
        self.gridLayout_4.addWidget(self.lcdNumber_MUX, 4, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setMaximumSize(QtCore.QSize(75, 50))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 6, 0, 1, 1)
        self.radioButton_MUX1 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_MUX1.setObjectName(_fromUtf8("radioButton_MUX1"))
        self.gridLayout_4.addWidget(self.radioButton_MUX1, 7, 0, 1, 1)
        self.radioButton_MUX2 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_MUX2.setObjectName(_fromUtf8("radioButton_MUX2"))
        self.gridLayout_4.addWidget(self.radioButton_MUX2, 7, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_5, 2, 5, 3, 4)
        self.horizontalSlider_Volume = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_Volume.setMaximum(50)
        self.horizontalSlider_Volume.setSingleStep(1)
        self.horizontalSlider_Volume.setPageStep(5)
        self.horizontalSlider_Volume.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Volume.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSlider_Volume.setTickInterval(5)
        self.horizontalSlider_Volume.setObjectName(_fromUtf8("horizontalSlider_Volume"))
        self.gridLayout.addWidget(self.horizontalSlider_Volume, 5, 5, 1, 4)
        self.comboBox_COM = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_COM.setObjectName(_fromUtf8("comboBox_COM"))
        self.gridLayout.addWidget(self.comboBox_COM, 0, 2, 1, 3)
        self.radioButton_Kanal2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_Kanal2.setObjectName(_fromUtf8("radioButton_Kanal2"))
        self.gridLayout.addWidget(self.radioButton_Kanal2, 1, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Audio Control", None))
        self.groupBox.setTitle(_translate("MainWindow", "SPDIF", None))
        self.label.setText(_translate("MainWindow", "Auswahl Audio Device", None))
        self.pushButton_Start.setText(_translate("MainWindow", "Start", None))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "I2C", None))
        self.label_3.setText(_translate("MainWindow", "Volt", None))
        self.label_6.setText(_translate("MainWindow", "Volt", None))
        self.label_4.setText(_translate("MainWindow", "Versorgungsspannung", None))
        self.label_5.setText(_translate("MainWindow", "Mittelwert Ausgangssignal", None))
        self.label_12.setText(_translate("MainWindow", "Abfragerate", None))
        self.radioButton_Kanal1.setText(_translate("MainWindow", "Kanal 1", None))
        self.label_2.setText(_translate("MainWindow", "Kanalauswahl", None))
        self.label_11.setText(_translate("MainWindow", "Auswahl COM Interface", None))
        self.label_8.setText(_translate("MainWindow", "Strom", None))
        self.label_13.setText(_translate("MainWindow", "Volume", None))
        self.label_9.setText(_translate("MainWindow", "MUX", None))
        self.label_7.setText(_translate("MainWindow", "Temperatur", None))
        self.label_10.setText(_translate("MainWindow", "Fehlerstatus", None))
        self.radioButton_MUX1.setText(_translate("MainWindow", "MUX 1", None))
        self.radioButton_MUX2.setText(_translate("MainWindow", "MUX 2", None))
        self.radioButton_Kanal2.setText(_translate("MainWindow", "Kanal 2", None))

from PyQt4 import Qwt5
